ALTER TABLE "users"
ADD COLUMN "created_at" TIMESTAMP default CURRENT_TIMESTAMP,
ADD COLUMN "updated_at" TIMESTAMP default CURRENT_TIMESTAMP;

ALTER TABLE "retrocards"
ADD COLUMN "created_at" TIMESTAMP default CURRENT_TIMESTAMP,
ADD COLUMN "updated_at" TIMESTAMP default CURRENT_TIMESTAMP;